port = 8080
gtfsrt {
    urls = ${?GTFSRT_URLS}
    pollInterval = "PT60S"
    pollInterval = ${?GTFSRT_POLL_INTERVAL}
    clientTimeout = "PT5S"
    clientTimeout = ${?GTFSRT_CLIENT_TIMEOUT}
}

mqtt {
    brokers = ${?MQTT_BROKERS}
    connectionTimeout = "PT5S"
    connectionTimeout = ${?MQTT_CONNECTION_TIMEOUT}
    keepAliveInterval = "PT30S"
    keepAliveInterval = ${?MQTT_KEEP_ALIVE_INTERVAL}
}