port = 8080
gtfsrt {
    urls = ${?GTFSRT_URLS}
    pollInterval = "PT30S"
    pollInterval = ${?GTFSRT_POLL_INTERVAL}
    clientTimeout = "PT5S"
    clientTimeout = ${?GTFSRT_CLIENT_TIMEOUT}
}

mqtt {
    brokers = ${?MQTT_BROKERS}
    clientId = "transitdata-metrics-exporter-local"
    clientId = ${?MQTT_CLIENT_ID}
    connectionTimeout = "PT15S"
    connectionTimeout = ${?MQTT_CONNECTION_TIMEOUT}
    keepAliveInterval = "PT20S"
    keepAliveInterval = ${?MQTT_KEEP_ALIVE_INTERVAL}
    qos = 0
    qos = ${?MQTT_QOS}
}